version: "3.8"
networks:
  app_network:
    driver: bridge

volumes:
  admin_data:
  frontend_data:
  backend_data:

services:
  admin:
    container_name: admin_container
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - admin_data:/app
    networks:
      - app_network
    stdin_open: true
    tty: true

  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - frontend_data:/app
    networks:
      - app_network
    stdin_open: true
    tty: true

  backend:
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - backend_data:/app
    env_file:
      - ./backend/ENV.env
    networks:
      - app_network
    stdin_open: true
    tty: true
